# Site settings
title: ｋｏｔａｅ
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Compendium of Japanese-language lessons that is updated with learning progression.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jensechu
github_username:  jensechu

# Build settings
markdown: kramdown
